# These are supported funding model platforms

github: # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
patreon: # Replace with a single Patreon username
open_collective: # Replace with a single Open Collective username
ko_fi: # Replace with a single Ko-fi username
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
community_bridge: # Replace with a single Community Bridge project-name e.g., cloud-foundry
liberapay: # Replace with a single Liberapay username
issuehunt: # Replace with a single IssueHunt username
otechie: # Replace with a single Otechie username
custom: ['http://m.qpic.cn/psc?/V12DgbRP0a1TXP/ruAMsa53pVQWN7FLK88i5v4.insf.ZHWVeORtvgzbl.vHII7E8ek5dARBRWrXiQl200fh19JT1dhkfbtR0fFThtQrqHbBn8Xxx3v9blYoEg!/b',
         'http://m.qpic.cn/psc?/V12DgbRP0a1TXP/45NBuzDIW489QBoVep5mcSWetEN.fWtw790qmGKuWtj0GVwIhckkAX.88GSFFJX4PqpthhQGL6oaPvOeVmb8muDqRmmKeUrI9eA.C6DMaQw!/b']
